// <auto-generated />
using System;
using AdminService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20261002080120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValuesJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.HasIndex("OwnerProfileId", "CreatedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("AdminService.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nhận diện biển số OCR tại cổng (có trong demo MVP)",
                            IsEnabled = true,
                            Key = "FEATURE_AI_LPR"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sơ đồ 2.5D/3D – stretch",
                            IsEnabled = false,
                            Key = "FEATURE_3D_MAP"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tìm bãi bằng giọng nói – stretch",
                            IsEnabled = false,
                            Key = "FEATURE_AI_VOICE_SEARCH"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chatbot FAQ – stretch",
                            IsEnabled = false,
                            Key = "FEATURE_AI_CHATBOT"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bãi quảng cáo trên kết quả tìm kiếm – Phase 2",
                            IsEnabled = false,
                            Key = "FEATURE_SPONSORED_LISTING"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vé tháng – Phase 2",
                            IsEnabled = false,
                            Key = "FEATURE_MONTHLY_PASS"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thanh toán online qua VNPAY sandbox",
                            IsEnabled = true,
                            Key = "FEATURE_VNPAY"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thanh toán VietQR động tại cổng ra",
                            IsEnabled = true,
                            Key = "FEATURE_VIETQR_AT_GATE"
                        });
                });

            modelBuilder.Entity("AdminService.Domain.Entities.Sanction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssuedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OwnerProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("ParkingLotId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId")
                        .HasFilter("[ParkingLotId] IS NOT NULL");

                    b.HasIndex("OwnerProfileId", "Status");

                    b.ToTable("Sanctions", (string)null);
                });

            modelBuilder.Entity("AdminService.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Thời gian giữ chỗ chờ thanh toán",
                            Key = "BOOKING_HOLD_MINUTES",
                            Value = "15"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Ân hạn chờ tài xế đến trễ",
                            Key = "CHECKIN_GRACE_PERIOD_MINUTES",
                            Value = "15"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Ân hạn miễn phí tính cước mỗi lượt",
                            Key = "PARKING_BILLING_GRACE_PERIOD_MINUTES",
                            Value = "15"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hủy trước ≥ 60 phút hoàn 100%, sau đó hoàn 0%",
                            Key = "CANCELLATION_WINDOW_MINUTES",
                            Value = "60"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Staff được hủy no-show sau mốc này",
                            Key = "NO_SHOW_CANCEL_AFTER_MINUTES",
                            Value = "30"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Bãi Mức 0 phải duyệt booking trong thời gian này",
                            Key = "MANUAL_LOT_APPROVAL_MINUTES",
                            Value = "10"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            Description = "Hoa hồng mặc định trên giao dịch hoàn tất",
                            Key = "DEFAULT_COMMISSION_RATE",
                            Value = "0.10"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            Description = "Chu kỳ quyết toán cho chủ bãi",
                            Key = "SETTLEMENT_CYCLE",
                            Value = "WEEKLY"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hiệu lực mã OTP",
                            Key = "OTP_EXPIRY_SECONDS",
                            Value = "300"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Số lần nhập sai OTP trước khi khóa",
                            Key = "OTP_MAX_ATTEMPTS",
                            Value = "3"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Thời gian khóa sau khi sai OTP",
                            Key = "OTP_LOCK_MINUTES",
                            Value = "15"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hiệu lực access token",
                            Key = "JWT_ACCESS_TOKEN_HOURS",
                            Value = "24"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hiệu lực refresh token",
                            Key = "JWT_REFRESH_TOKEN_DAYS",
                            Value = "7"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Số xe tối đa trong Garage cá nhân",
                            Key = "MAX_VEHICLES_PER_USER",
                            Value = "10"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            Description = "Bán kính tìm bãi mặc định",
                            Key = "SEARCH_RADIUS_KM",
                            Value = "5"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Biên an toàn chiều cao xe so với trần",
                            Key = "HEIGHT_CLEARANCE_MARGIN_CM",
                            Value = "10"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Chu kỳ kiểm tra kết nối bãi",
                            Key = "HEARTBEAT_INTERVAL_SECONDS",
                            Value = "60"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Số lần mất kết nối trước khi đánh dấu Stale",
                            Key = "HEARTBEAT_MAX_FAILURES",
                            Value = "3"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            Description = "Ngưỡng tự mở barie theo kết quả OCR",
                            Key = "OCR_AUTO_OPEN_MIN_CONFIDENCE",
                            Value = "0.90"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hạn chủ bãi phản hồi tranh chấp",
                            Key = "OWNER_DISPUTE_RESPONSE_HOURS",
                            Value = "48"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hạn gửi khiếu nại sau sự việc",
                            Key = "COMPLAINT_WINDOW_DAYS",
                            Value = "7"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Hạn cập nhật sơ đồ sau thay đổi thực tế",
                            Key = "LAYOUT_UPDATE_DEADLINE_HOURS",
                            Value = "48"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            Description = "Phí chiếm dụng trụ sạc sau 30 phút sạc đầy",
                            Key = "EV_IDLE_FEE_PER_15_MINUTES",
                            Value = "20000"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Giới hạn request/phút cho mỗi client",
                            Key = "API_RATE_LIMIT_PER_MINUTE",
                            Value = "100"
                        });
                });

            modelBuilder.Entity("ParkingManagement.SharedKernel.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
