<Project Sdk="Microsoft.NET.Sdk">
  <!-- APPLICATION: Use case, DTO, interface (port) cho Infrastructure. Chá»‰ phá»¥ thuá»™c Domain. -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ParkingService.Domain\ParkingService.Domain.csproj" />
  </ItemGroup>
</Project>