CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(150) NOT NULL,
        "Email" character varying(256),
        "PhoneNumber" character varying(20),
        "EmailConfirmed" boolean NOT NULL,
        "PhoneConfirmed" boolean NOT NULL,
        "PasswordHash" character varying(200) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "LockedUntilUtc" timestamp with time zone,
        "LockReason" character varying(500),
        "FailedLoginCount" integer NOT NULL,
        "LastLoginAtUtc" timestamp with time zone,
        "AvatarUrl" character varying(512),
        "KycStatus" character varying(40) NOT NULL,
        "KycDocumentType" character varying(40),
        "KycNumberEncrypted" character varying(512),
        "KycFrontImageUrl" character varying(512),
        "KycBackImageUrl" character varying(512),
        "KycVerifiedAtUtc" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Users_EmailOrPhone" CHECK ("Email" IS NOT NULL OR "PhoneNumber" IS NOT NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "DataSubjectRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "RequestType" character varying(40) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Reason" character varying(1000),
        "DueAtUtc" timestamp with time zone NOT NULL,
        "HandledByUserId" integer,
        "CompletedAtUtc" timestamp with time zone,
        "ResultNote" character varying(1000),
        "ExportFileUrl" character varying(512),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_DataSubjectRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DataSubjectRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "OtpCodes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer,
        "Destination" character varying(256) NOT NULL,
        "CodeHash" character varying(200) NOT NULL,
        "Purpose" character varying(40) NOT NULL,
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "AttemptCount" integer NOT NULL,
        "ConsumedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OtpCodes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OtpCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "OwnerProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "BusinessName" character varying(200) NOT NULL,
        "TaxCode" character varying(20),
        "BusinessAddress" character varying(500),
        "BankBin" character varying(10) NOT NULL,
        "BankName" character varying(100) NOT NULL,
        "BankAccountNumber" character varying(30) NOT NULL,
        "BankAccountName" character varying(100) NOT NULL,
        "CommissionRateOverride" numeric(5,4),
        "IsLocked" boolean NOT NULL,
        "Status" character varying(40) NOT NULL,
        "ExitRequestedAtUtc" timestamp with time zone,
        "ExitEffectiveAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OwnerProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OwnerProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "TokenHash" character varying(200) NOT NULL,
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "RevokedAtUtc" timestamp with time zone,
        "ReplacedByTokenHash" character varying(200),
        "CreatedByIp" character varying(45),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "SecurityEvents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer,
        "EventType" character varying(40) NOT NULL,
        "Identifier" character varying(256),
        "IpAddress" character varying(45),
        "UserAgent" character varying(512),
        "Detail" character varying(1000),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_SecurityEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SecurityEvents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "UserRoles" (
        "UserId" integer NOT NULL,
        "Role" character varying(40) NOT NULL,
        "GrantedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "Role"),
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE TABLE "StaffAssignments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StaffUserId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "ParkingLotId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "RevokedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_StaffAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StaffAssignments_OwnerProfiles_OwnerProfileId" FOREIGN KEY ("OwnerProfileId") REFERENCES "OwnerProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StaffAssignments_Users_StaffUserId" FOREIGN KEY ("StaffUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_DataSubjectRequests_Status_DueAtUtc" ON "DataSubjectRequests" ("Status", "DueAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_DataSubjectRequests_UserId" ON "DataSubjectRequests" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_OtpCodes_Destination_Purpose_ExpiresAtUtc" ON "OtpCodes" ("Destination", "Purpose", "ExpiresAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_OtpCodes_UserId" ON "OtpCodes" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_OwnerProfiles_UserId" ON "OwnerProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_SecurityEvents_Identifier_EventType_CreatedAtUtc" ON "SecurityEvents" ("Identifier", "EventType", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_SecurityEvents_UserId_CreatedAtUtc" ON "SecurityEvents" ("UserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_StaffAssignments_OwnerProfileId" ON "StaffAssignments" ("OwnerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_StaffAssignments_ParkingLotId" ON "StaffAssignments" ("ParkingLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_StaffAssignments_StaffUserId_ParkingLotId" ON "StaffAssignments" ("StaffUserId", "ParkingLotId") WHERE "IsActive" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email") WHERE "Email" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_PhoneNumber" ON "Users" ("PhoneNumber") WHERE "PhoneNumber" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    CREATE INDEX "IX_Users_Status" ON "Users" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102527_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003102527_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

