CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE TABLE "Vehicles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "PlateNumber" character varying(15) NOT NULL,
        "PlateDisplay" character varying(20) NOT NULL,
        "VehicleType" character varying(40) NOT NULL,
        "FuelType" character varying(40) NOT NULL,
        "Brand" character varying(50),
        "Model" character varying(50),
        "Color" character varying(30),
        "LengthCm" integer,
        "WidthCm" integer,
        "HeightCm" integer NOT NULL,
        "IsEmergencyVehicle" boolean NOT NULL,
        "IsDefault" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Vehicles_Height" CHECK ("HeightCm" > 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE TABLE "VehicleShares" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VehicleId" integer NOT NULL,
        "OwnerUserId" integer NOT NULL,
        "SharedWithUserId" integer NOT NULL,
        "Status" character varying(40) NOT NULL,
        "ExpiresAtUtc" timestamp with time zone,
        "RevokedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_VehicleShares" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_VehicleShares_NotSelf" CHECK ("OwnerUserId" <> "SharedWithUserId"),
        CONSTRAINT "FK_VehicleShares_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE INDEX "IX_Vehicles_PlateNumber" ON "Vehicles" ("PlateNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Vehicles_UserId_PlateNumber" ON "Vehicles" ("UserId", "PlateNumber") WHERE "IsDeleted" = FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE INDEX "IX_VehicleShares_SharedWithUserId" ON "VehicleShares" ("SharedWithUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_VehicleShares_VehicleId_SharedWithUserId" ON "VehicleShares" ("VehicleId", "SharedWithUserId") WHERE "Status" <> 'Revoked';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102633_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003102633_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

