CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "ExternalParkingLots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Address" character varying(500) NOT NULL,
        "City" character varying(100),
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "ReferencePricePerHour" numeric(18,2),
        "OpeningHoursText" character varying(200),
        "Source" character varying(200),
        "ImportedByUserId" integer NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ExternalParkingLots" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "ParkingLots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerProfileId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Address" character varying(500) NOT NULL,
        "City" character varying(100) NOT NULL,
        "District" character varying(100),
        "Description" character varying(2000),
        "HotlinePhone" character varying(20),
        "CoverImageUrl" character varying(512),
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "TotalSlots" integer NOT NULL,
        "AvailableSlots" integer NOT NULL,
        "MaxHeightCm" integer NOT NULL,
        "OpenTime" time without time zone NOT NULL,
        "CloseTime" time without time zone NOT NULL,
        "Status" character varying(40) NOT NULL,
        "IntegrationTier" character varying(40) NOT NULL,
        "RatingAverage" numeric(3,2) NOT NULL,
        "RatingCount" integer NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ParkingLots" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ParkingLots_Latitude" CHECK ("Latitude" BETWEEN -90 AND 90),
        CONSTRAINT "CK_ParkingLots_Longitude" CHECK ("Longitude" BETWEEN -180 AND 180),
        CONSTRAINT "CK_ParkingLots_Slots" CHECK ("AvailableSlots" >= 0 AND "AvailableSlots" <= "TotalSlots")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "ClosureSchedules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "TargetType" character varying(40) NOT NULL,
        "TargetId" integer NOT NULL,
        "StartsAtUtc" timestamp with time zone NOT NULL,
        "EndsAtUtc" timestamp with time zone,
        "Reason" character varying(500) NOT NULL,
        "IsEmergency" boolean NOT NULL,
        "AffectedBookingsNotified" boolean NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "CancelledAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ClosureSchedules" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ClosureSchedules_Period" CHECK ("EndsAtUtc" IS NULL OR "EndsAtUtc" > "StartsAtUtc"),
        CONSTRAINT "FK_ClosureSchedules_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "KybApplications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "Status" character varying(40) NOT NULL,
        "BusinessLicenseUrl" character varying(512),
        "SitePhotoUrlsJson" text,
        "PhotoLatitude" double precision,
        "PhotoLongitude" double precision,
        "FireSafetyCertificateUrl" character varying(512),
        "FieldSurveyRequired" boolean NOT NULL,
        "FieldSurveyAtUtc" timestamp with time zone,
        "FieldSurveyNote" character varying(2000),
        "SubmittedAtUtc" timestamp with time zone,
        "ReviewedByUserId" integer,
        "ReviewedAtUtc" timestamp with time zone,
        "RejectReason" character varying(1000),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_KybApplications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_KybApplications_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "LotAmenities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "Code" character varying(40) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Note" character varying(200),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LotAmenities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LotAmenities_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "LotCapacityConfigs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "OnlineQuota" integer NOT NULL,
        "WalkInBufferPercent" integer NOT NULL,
        "OnlineLockThreshold" integer NOT NULL,
        "InstantBookingPaused" boolean NOT NULL,
        "IsEmergencyStopped" boolean NOT NULL,
        "EmergencyReason" character varying(500),
        "LastHeartbeatAtUtc" timestamp with time zone,
        "ConsecutiveHeartbeatFailures" integer NOT NULL,
        "IsStale" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LotCapacityConfigs" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_LotCapacity_Buffer" CHECK ("WalkInBufferPercent" BETWEEN 0 AND 100),
        CONSTRAINT "FK_LotCapacityConfigs_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "LotIntegrations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "ProviderName" character varying(100) NOT NULL,
        "ApiKeyPrefix" character varying(12) NOT NULL,
        "ApiKeyHash" character varying(200) NOT NULL,
        "WebhookUrl" character varying(512),
        "WebhookSecretHash" character varying(200),
        "Status" character varying(40) NOT NULL,
        "LastSyncAtUtc" timestamp with time zone,
        "LastError" character varying(1000),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LotIntegrations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LotIntegrations_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "LotOperatingHours" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "DayOfWeek" character varying(40) NOT NULL,
        "OpenTime" time without time zone NOT NULL,
        "CloseTime" time without time zone NOT NULL,
        "IsClosed" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LotOperatingHours" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LotOperatingHours_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "LotPhotos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "Url" character varying(512) NOT NULL,
        "Caption" character varying(200),
        "SortOrder" integer NOT NULL,
        "IsCover" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LotPhotos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LotPhotos_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "Zones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "Code" character varying(20) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "IsOutdoor" boolean NOT NULL,
        "IsClosed" boolean NOT NULL,
        "ClosedReason" character varying(500),
        "SortOrder" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Zones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Zones_ParkingLots_ParkingLotId" FOREIGN KEY ("ParkingLotId") REFERENCES "ParkingLots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "Floors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ZoneId" integer NOT NULL,
        "Name" character varying(50) NOT NULL,
        "Level" integer NOT NULL,
        "MaxHeightCm" integer,
        "MaxWeightKg" integer,
        "GridColumns" integer NOT NULL,
        "GridRows" integer NOT NULL,
        "IsClosed" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Floors" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Floors_Grid" CHECK ("GridColumns" > 0 AND "GridRows" > 0),
        CONSTRAINT "FK_Floors_Zones_ZoneId" FOREIGN KEY ("ZoneId") REFERENCES "Zones" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "LayoutVersions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FloorId" integer NOT NULL,
        "VersionNo" integer NOT NULL,
        "LayoutJson" text NOT NULL,
        "IsPublished" boolean NOT NULL,
        "PublishedAtUtc" timestamp with time zone,
        "CreatedByUserId" integer NOT NULL,
        "ChangeNote" character varying(500),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LayoutVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LayoutVersions_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES "Floors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "Slots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FloorId" integer NOT NULL,
        "Code" character varying(20) NOT NULL,
        "SlotType" character varying(40) NOT NULL,
        "MaxVehicleType" character varying(40) NOT NULL,
        "GridX" integer NOT NULL,
        "GridY" integer NOT NULL,
        "WidthCells" integer NOT NULL,
        "HeightCells" integer NOT NULL,
        "State" character varying(40) NOT NULL,
        "StateChangedAtUtc" timestamp with time zone,
        "DedicatedVehicleId" integer,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Slots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Slots_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES "Floors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE TABLE "SlotStateLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SlotId" integer NOT NULL,
        "FromState" character varying(40) NOT NULL,
        "ToState" character varying(40) NOT NULL,
        "Source" character varying(40) NOT NULL,
        "BookingId" integer,
        "ParkingSessionId" integer,
        "ChangedByUserId" integer,
        "Reason" character varying(500),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_SlotStateLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SlotStateLogs_Slots_SlotId" FOREIGN KEY ("SlotId") REFERENCES "Slots" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ClosureSchedules_ParkingLotId_StartsAtUtc_EndsAtUtc" ON "ClosureSchedules" ("ParkingLotId", "StartsAtUtc", "EndsAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ClosureSchedules_TargetType_TargetId" ON "ClosureSchedules" ("TargetType", "TargetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ExternalParkingLots_Latitude_Longitude" ON "ExternalParkingLots" ("Latitude", "Longitude");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Floors_ZoneId_Name" ON "Floors" ("ZoneId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_KybApplications_ParkingLotId_Status" ON "KybApplications" ("ParkingLotId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_KybApplications_Status" ON "KybApplications" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LayoutVersions_FloorId_VersionNo" ON "LayoutVersions" ("FloorId", "VersionNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_LotAmenities_Code" ON "LotAmenities" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LotAmenities_ParkingLotId_Code" ON "LotAmenities" ("ParkingLotId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LotCapacityConfigs_ParkingLotId" ON "LotCapacityConfigs" ("ParkingLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LotIntegrations_ApiKeyPrefix" ON "LotIntegrations" ("ApiKeyPrefix");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LotIntegrations_ParkingLotId" ON "LotIntegrations" ("ParkingLotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_LotOperatingHours_ParkingLotId_DayOfWeek" ON "LotOperatingHours" ("ParkingLotId", "DayOfWeek");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_LotPhotos_ParkingLotId_SortOrder" ON "LotPhotos" ("ParkingLotId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "UX_LotPhotos_OneCover" ON "LotPhotos" ("ParkingLotId") WHERE "IsCover" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ParkingLots_City_District" ON "ParkingLots" ("City", "District");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ParkingLots_Latitude_Longitude" ON "ParkingLots" ("Latitude", "Longitude");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ParkingLots_OwnerProfileId" ON "ParkingLots" ("OwnerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_ParkingLots_Status" ON "ParkingLots" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_Slots_DedicatedVehicleId" ON "Slots" ("DedicatedVehicleId") WHERE "DedicatedVehicleId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Slots_FloorId_Code" ON "Slots" ("FloorId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Slots_FloorId_GridX_GridY" ON "Slots" ("FloorId", "GridX", "GridY");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_Slots_FloorId_State" ON "Slots" ("FloorId", "State");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_SlotStateLogs_SlotId_CreatedAtUtc" ON "SlotStateLogs" ("SlotId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE INDEX "IX_SlotStateLogs_Source_CreatedAtUtc" ON "SlotStateLogs" ("Source", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Zones_ParkingLotId_Code" ON "Zones" ("ParkingLotId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102631_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003102631_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

