CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE TABLE "Bookings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "UserId" integer NOT NULL,
        "VehicleId" integer NOT NULL,
        "PlateNumber" character varying(15) NOT NULL,
        "VehicleType" character varying(40) NOT NULL,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "ParkingLotName" character varying(200) NOT NULL,
        "ZoneId" integer,
        "SlotId" integer,
        "SlotCode" character varying(20),
        "AllocationMode" character varying(40) NOT NULL,
        "StartAtUtc" timestamp with time zone NOT NULL,
        "EndAtUtc" timestamp with time zone NOT NULL,
        "HoldExpiresAtUtc" timestamp with time zone,
        "ConfirmedAtUtc" timestamp with time zone,
        "CheckedInAtUtc" timestamp with time zone,
        "CheckedOutAtUtc" timestamp with time zone,
        "CompletedAtUtc" timestamp with time zone,
        "CancelledAtUtc" timestamp with time zone,
        "CancelReason" character varying(500),
        "CancelledByUserId" integer,
        "Status" character varying(40) NOT NULL,
        "RequiresOwnerApproval" boolean NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "DiscountAmount" numeric(18,2) NOT NULL,
        "PaidAmount" numeric(18,2) NOT NULL,
        "PromotionId" integer,
        "PromotionCode" character varying(30),
        "QrToken" character varying(1000),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Bookings_Amount" CHECK ("TotalAmount" >= 0 AND "DiscountAmount" >= 0 AND "PaidAmount" >= 0),
        CONSTRAINT "CK_Bookings_Time" CHECK ("EndAtUtc" > "StartAtUtc")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE TABLE "MonthlyPasses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "UserId" integer NOT NULL,
        "VehicleId" integer NOT NULL,
        "PlateNumber" character varying(15) NOT NULL,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "SlotId" integer,
        "SlotCode" character varying(20),
        "ValidFrom" date NOT NULL,
        "ValidTo" date NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "AutoRenew" boolean NOT NULL,
        "Status" character varying(40) NOT NULL,
        "PaymentId" integer,
        "CancelledAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_MonthlyPasses" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_MonthlyPasses_Period" CHECK ("ValidTo" >= "ValidFrom")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE TABLE "BookingModifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "ModificationType" character varying(40) NOT NULL,
        "OldStartAtUtc" timestamp with time zone,
        "OldEndAtUtc" timestamp with time zone,
        "NewStartAtUtc" timestamp with time zone,
        "NewEndAtUtc" timestamp with time zone,
        "OldVehicleId" integer,
        "NewVehicleId" integer,
        "OldSlotId" integer,
        "NewSlotId" integer,
        "PriceDifference" numeric(18,2) NOT NULL,
        "PaymentId" integer,
        "RequestedByUserId" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_BookingModifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingModifications_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE TABLE "BookingStatusLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "FromStatus" character varying(40),
        "ToStatus" character varying(40) NOT NULL,
        "ChangedByUserId" integer,
        "Reason" character varying(500),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_BookingStatusLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingStatusLogs_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE TABLE "PriceSnapshots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "RateCardId" integer NOT NULL,
        "RateCardJson" text NOT NULL,
        "BaseAmount" numeric(18,2) NOT NULL,
        "SurchargeAmount" numeric(18,2) NOT NULL,
        "DiscountAmount" numeric(18,2) NOT NULL,
        "FinalAmount" numeric(18,2) NOT NULL,
        "BillingGracePeriodMinutes" integer NOT NULL,
        "OverstayMultiplier" numeric(4,2) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PriceSnapshots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PriceSnapshots_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_BookingModifications_BookingId_CreatedAtUtc" ON "BookingModifications" ("BookingId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Bookings_Code" ON "Bookings" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_OwnerProfileId_ParkingLotId_StartAtUtc" ON "Bookings" ("OwnerProfileId", "ParkingLotId", "StartAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_PlateNumber" ON "Bookings" ("PlateNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_SlotId_StartAtUtc_EndAtUtc" ON "Bookings" ("SlotId", "StartAtUtc", "EndAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_Status_HoldExpiresAtUtc" ON "Bookings" ("Status", "HoldExpiresAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_UserId_Status" ON "Bookings" ("UserId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_BookingStatusLogs_BookingId_CreatedAtUtc" ON "BookingStatusLogs" ("BookingId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_MonthlyPasses_Code" ON "MonthlyPasses" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_MonthlyPasses_ParkingLotId_PlateNumber_Status" ON "MonthlyPasses" ("ParkingLotId", "PlateNumber", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_MonthlyPasses_SlotId" ON "MonthlyPasses" ("SlotId") WHERE "SlotId" IS NOT NULL AND "Status" = 'Active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_MonthlyPasses_UserId" ON "MonthlyPasses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PriceSnapshots_BookingId" ON "PriceSnapshots" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102705_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003102705_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

