CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "Holidays" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Date" date NOT NULL,
        "Name" character varying(100) NOT NULL,
        "City" character varying(100),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Holidays" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "BookingId" integer,
        "BookingCode" character varying(30),
        "ParkingSessionId" integer,
        "UserId" integer,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "Purpose" character varying(40) NOT NULL,
        "Method" character varying(40) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "RefundedAmount" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "IdempotencyKey" character varying(100) NOT NULL,
        "ProviderTransactionId" character varying(100),
        "ProviderResponseCode" character varying(20),
        "RawCallbackJson" text,
        "TransferContent" character varying(100),
        "PaidAtUtc" timestamp with time zone,
        "ExpiresAtUtc" timestamp with time zone,
        "ConfirmedByStaffId" integer,
        "RetryCount" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Payments_Amount" CHECK ([Amount] >= 0 AND [RefundedAmount] >= 0 AND [RefundedAmount] <= [Amount]),
        CONSTRAINT "CK_Payments_Target" CHECK ([BookingId] IS NOT NULL OR [ParkingSessionId] IS NOT NULL)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "Promotions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "ParkingLotId" integer,
        "OwnerProfileId" integer,
        "Sponsor" character varying(40) NOT NULL,
        "DiscountType" character varying(40) NOT NULL,
        "DiscountValue" numeric(18,2) NOT NULL,
        "MaxDiscountAmount" numeric(18,2),
        "MinOrderAmount" numeric(18,2),
        "StartsAtUtc" timestamp with time zone NOT NULL,
        "EndsAtUtc" timestamp with time zone NOT NULL,
        "UsageLimit" integer,
        "UsedCount" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Promotions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Promotions_Period" CHECK ([EndsAtUtc] > [StartsAtUtc])
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "RateCards" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "EffectiveFromUtc" timestamp with time zone NOT NULL,
        "EffectiveToUtc" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "OvernightSurcharge" numeric(18,2) NOT NULL,
        "WeekendMultiplier" numeric(4,2) NOT NULL,
        "HolidayMultiplier" numeric(4,2) NOT NULL,
        "OversizedMultiplier" numeric(4,2) NOT NULL,
        "OverstayMultiplier" numeric(4,2) NOT NULL,
        "MaxDailyAmount" numeric(18,2),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_RateCards" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RateCards_Multipliers" CHECK ([WeekendMultiplier] > 0 AND [HolidayMultiplier] > 0 AND [OversizedMultiplier] >= 1 AND [OverstayMultiplier] >= 1)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "Settlements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerProfileId" integer NOT NULL,
        "PeriodStart" date NOT NULL,
        "PeriodEnd" date NOT NULL,
        "GrossAmount" numeric(18,2) NOT NULL,
        "CommissionRate" numeric(5,4) NOT NULL,
        "CommissionAmount" numeric(18,2) NOT NULL,
        "RefundAmount" numeric(18,2) NOT NULL,
        "HeldAmount" numeric(18,2) NOT NULL,
        "AdjustmentAmount" numeric(18,2) NOT NULL,
        "NetPayout" numeric(18,2) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "ApprovedByUserId" integer,
        "ApprovedAtUtc" timestamp with time zone,
        "PaidAtUtc" timestamp with time zone,
        "PayoutReference" character varying(100),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Settlements" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Settlements_Period" CHECK ([PeriodEnd] >= [PeriodStart])
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "CompensationVouchers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "UserId" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Reason" character varying(500) NOT NULL,
        "BookingId" integer,
        "ComplaintId" integer,
        "ChargedToOwnerProfileId" integer,
        "ExpiresAtUtc" timestamp with time zone NOT NULL,
        "Status" character varying(40) NOT NULL,
        "RedeemedAtUtc" timestamp with time zone,
        "RedeemedPaymentId" integer,
        "IssuedByUserId" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_CompensationVouchers" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CompensationVouchers_Amount" CHECK ([Amount] > 0),
        CONSTRAINT "FK_CompensationVouchers_Payments_RedeemedPaymentId" FOREIGN KEY ("RedeemedPaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "PaymentCallbackLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PaymentId" integer,
        "Provider" character varying(40) NOT NULL,
        "ProviderTransactionId" character varying(100),
        "RawPayload" text NOT NULL,
        "SignatureValid" boolean NOT NULL,
        "IsDuplicate" boolean NOT NULL,
        "ResultCode" character varying(20),
        "ProcessingError" character varying(1000),
        "SourceIp" character varying(45),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PaymentCallbackLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PaymentCallbackLogs_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "Refunds" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PaymentId" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Reason" character varying(40) NOT NULL,
        "Note" character varying(1000),
        "Status" character varying(40) NOT NULL,
        "ComplaintId" integer,
        "RequestedByUserId" integer,
        "ApprovedByUserId" integer,
        "ProviderRefundId" character varying(100),
        "ProcessedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Refunds" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Refunds_Amount" CHECK ([Amount] > 0),
        CONSTRAINT "FK_Refunds_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "PromotionRedemptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PromotionId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "BookingId" integer NOT NULL,
        "PaymentId" integer,
        "DiscountAmount" numeric(18,2) NOT NULL,
        "IsReverted" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PromotionRedemptions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_PromotionRedemptions_Amount" CHECK ([DiscountAmount] >= 0),
        CONSTRAINT "FK_PromotionRedemptions_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PromotionRedemptions_Promotions_PromotionId" FOREIGN KEY ("PromotionId") REFERENCES "Promotions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "RateRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RateCardId" integer NOT NULL,
        "VehicleType" character varying(40) NOT NULL,
        "FromMinute" integer NOT NULL,
        "ToMinute" integer,
        "BlockMinutes" integer NOT NULL,
        "PricePerBlock" numeric(18,2) NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_RateRules" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RateRules_Block" CHECK ([BlockMinutes] > 0 AND [PricePerBlock] >= 0),
        CONSTRAINT "CK_RateRules_Range" CHECK ([ToMinute] IS NULL OR [ToMinute] > [FromMinute]),
        CONSTRAINT "FK_RateRules_RateCards_RateCardId" FOREIGN KEY ("RateCardId") REFERENCES "RateCards" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "FinancialAdjustments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerProfileId" integer NOT NULL,
        "SettlementId" integer,
        "Amount" numeric(18,2) NOT NULL,
        "Reason" character varying(500) NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_FinancialAdjustments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FinancialAdjustments_Settlements_SettlementId" FOREIGN KEY ("SettlementId") REFERENCES "Settlements" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "Invoices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" character varying(40) NOT NULL,
        "PaymentId" integer,
        "SettlementId" integer,
        "InvoiceNumber" character varying(30) NOT NULL,
        "BuyerName" character varying(200) NOT NULL,
        "BuyerTaxCode" character varying(20),
        "BuyerEmail" character varying(256),
        "SubTotal" numeric(18,2) NOT NULL,
        "VatAmount" numeric(18,2) NOT NULL,
        "Total" numeric(18,2) NOT NULL,
        "IssuedAtUtc" timestamp with time zone NOT NULL,
        "PdfUrl" character varying(512),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Invoices_Source" CHECK (([Type] = N'ParkingFee' AND [PaymentId] IS NOT NULL) OR ([Type] = N'PlatformCommission' AND [SettlementId] IS NOT NULL)),
        CONSTRAINT "FK_Invoices_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Invoices_Settlements_SettlementId" FOREIGN KEY ("SettlementId") REFERENCES "Settlements" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE TABLE "SettlementLines" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SettlementId" integer NOT NULL,
        "LineType" character varying(40) NOT NULL,
        "PaymentId" integer,
        "RefundId" integer,
        "ParkingLotId" integer NOT NULL,
        "ReferenceCode" character varying(30),
        "Amount" numeric(18,2) NOT NULL,
        "CommissionAmount" numeric(18,2) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_SettlementLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SettlementLines_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SettlementLines_Refunds_RefundId" FOREIGN KEY ("RefundId") REFERENCES "Refunds" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_SettlementLines_Settlements_SettlementId" FOREIGN KEY ("SettlementId") REFERENCES "Settlements" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (1, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-01-01', 'Tết Dương lịch', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (2, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-02-05', 'Tết Nguyên đán (29 Tết)', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (3, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-02-06', 'Tết Nguyên đán (Mùng 1)', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (4, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-02-07', 'Tết Nguyên đán (Mùng 2)', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (5, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-02-08', 'Tết Nguyên đán (Mùng 3)', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (6, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-02-09', 'Tết Nguyên đán (Mùng 4)', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (7, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-04-16', 'Giỗ Tổ Hùng Vương', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (8, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-04-30', 'Ngày Giải phóng miền Nam', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (9, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-05-01', 'Quốc tế Lao động', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (10, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-09-02', 'Quốc khánh', NULL);
    INSERT INTO "Holidays" ("Id", "City", "CreatedAtUtc", "Date", "Name", "UpdatedAtUtc")
    VALUES (11, NULL, TIMESTAMPTZ '2026-10-01T00:00:00Z', DATE '2027-09-03', 'Quốc khánh (nghỉ liền kề)', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_CompensationVouchers_ChargedToOwnerProfileId" ON "CompensationVouchers" ("ChargedToOwnerProfileId") WHERE [ChargedToOwnerProfileId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CompensationVouchers_Code" ON "CompensationVouchers" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_CompensationVouchers_RedeemedPaymentId" ON "CompensationVouchers" ("RedeemedPaymentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_CompensationVouchers_UserId_Status_ExpiresAtUtc" ON "CompensationVouchers" ("UserId", "Status", "ExpiresAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_FinancialAdjustments_OwnerProfileId" ON "FinancialAdjustments" ("OwnerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_FinancialAdjustments_SettlementId" ON "FinancialAdjustments" ("SettlementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Holidays_Date_City" ON "Holidays" ("Date", "City");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Invoices_InvoiceNumber" ON "Invoices" ("InvoiceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Invoices_PaymentId" ON "Invoices" ("PaymentId") WHERE [PaymentId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Invoices_SettlementId" ON "Invoices" ("SettlementId") WHERE [SettlementId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_PaymentCallbackLogs_PaymentId_CreatedAtUtc" ON "PaymentCallbackLogs" ("PaymentId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_PaymentCallbackLogs_Provider_ProviderTransactionId" ON "PaymentCallbackLogs" ("Provider", "ProviderTransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_Payments_BookingId" ON "Payments" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_Code" ON "Payments" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_IdempotencyKey" ON "Payments" ("IdempotencyKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_Method_ProviderTransactionId" ON "Payments" ("Method", "ProviderTransactionId") WHERE [ProviderTransactionId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_Payments_OwnerProfileId_Status_PaidAtUtc" ON "Payments" ("OwnerProfileId", "Status", "PaidAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_Payments_ParkingSessionId" ON "Payments" ("ParkingSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PromotionRedemptions_BookingId" ON "PromotionRedemptions" ("BookingId") WHERE [IsReverted] = 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_PromotionRedemptions_PaymentId" ON "PromotionRedemptions" ("PaymentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_PromotionRedemptions_PromotionId_UserId" ON "PromotionRedemptions" ("PromotionId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Promotions_Code" ON "Promotions" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_Promotions_ParkingLotId_IsActive" ON "Promotions" ("ParkingLotId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_RateCards_OwnerProfileId" ON "RateCards" ("OwnerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_RateCards_ParkingLotId_IsActive_EffectiveFromUtc" ON "RateCards" ("ParkingLotId", "IsActive", "EffectiveFromUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_RateRules_RateCardId_VehicleType_FromMinute" ON "RateRules" ("RateCardId", "VehicleType", "FromMinute");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_Refunds_ComplaintId" ON "Refunds" ("ComplaintId") WHERE [ComplaintId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_Refunds_PaymentId_Status" ON "Refunds" ("PaymentId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_SettlementLines_PaymentId" ON "SettlementLines" ("PaymentId") WHERE [PaymentId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_SettlementLines_RefundId" ON "SettlementLines" ("RefundId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE INDEX "IX_SettlementLines_SettlementId" ON "SettlementLines" ("SettlementId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Settlements_OwnerProfileId_PeriodStart" ON "Settlements" ("OwnerProfileId", "PeriodStart");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Holidays"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Holidays") + 1,
            nextval(pg_get_serial_sequence('"Holidays"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092328_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003092328_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

