CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE TABLE "DeviceTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Token" character varying(512) NOT NULL,
        "Platform" character varying(40) NOT NULL,
        "DeviceName" character varying(100),
        "LastUsedAtUtc" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_DeviceTokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE TABLE "NotificationPreferences" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "TemplateKey" character varying(50) NOT NULL,
        "Channel" character varying(40) NOT NULL,
        "IsEnabled" boolean NOT NULL,
        "QuietFrom" time without time zone,
        "QuietTo" time without time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE TABLE "NotificationTemplates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(50) NOT NULL,
        "Channel" character varying(40) NOT NULL,
        "TitleTemplate" character varying(200) NOT NULL,
        "BodyTemplate" character varying(2000) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_NotificationTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "TemplateId" integer,
        "Channel" character varying(40) NOT NULL,
        "TemplateKey" character varying(50) NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Body" character varying(2000) NOT NULL,
        "DataJson" text,
        "Status" character varying(40) NOT NULL,
        "RetryCount" integer NOT NULL,
        "LastError" character varying(1000),
        "SentAtUtc" timestamp with time zone,
        "IsRead" boolean NOT NULL,
        "ReadAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_NotificationTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "NotificationTemplates" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (1, 'Mã OTP Smart Parking của bạn là {Code}, hiệu lực 5 phút.', 'Sms', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'OTP_CODE', 'Mã xác thực', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (2, 'Booking {BookingCode} tại {LotName} lúc {StartAt} đã được xác nhận.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'BOOKING_CONFIRMED', 'Đặt chỗ thành công', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (3, 'Bạn đã đặt chỗ tại {LotName}, slot {SlotCode}, từ {StartAt} đến {EndAt}. Số tiền: {Amount}.', 'Email', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'BOOKING_CONFIRMED', 'Xác nhận đặt chỗ {BookingCode}', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (4, 'Booking {BookingCode} đã hết 15 phút giữ chỗ do chưa thanh toán.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'BOOKING_HOLD_EXPIRED', 'Hết thời gian giữ chỗ', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (5, 'Booking {BookingCode} bắt đầu lúc {StartAt}. Bạn có 15 phút ân hạn khi đến trễ.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'BOOKING_REMINDER', 'Sắp đến giờ đỗ xe', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (6, 'Booking {BookingCode} đã hủy. Hoàn tiền: {RefundAmount}.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'BOOKING_CANCELLED', 'Đã hủy booking', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (7, 'Booking {BookingCode} đã bị hủy vì quá 30 phút chưa check-in.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'BOOKING_NO_SHOW', 'Booking bị hủy do không đến', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (8, 'Xe {PlateNumber} đã vào {LotName} lúc {EntryAt}.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'CHECKIN_SUCCESS', 'Xe đã vào bãi', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (9, 'Xe {PlateNumber} ra lúc {ExitAt}. Tổng phí: {Amount}.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'CHECKOUT_RECEIPT', 'Xe đã ra bãi', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (10, 'Thanh toán cho {BookingCode} không thành công. Vui lòng thử lại.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'PAYMENT_FAILED', 'Thanh toán thất bại', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (11, 'Bãi {LotName} đã được duyệt và hiển thị trên Smart Parking.', 'Email', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'KYB_APPROVED', 'Bãi xe đã được duyệt', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (12, 'Hồ sơ bãi {LotName} chưa được duyệt. Lý do: {Reason}.', 'Email', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'KYB_REJECTED', 'Hồ sơ bãi xe cần bổ sung', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (13, 'Khiếu nại {ComplaintCode} cho bãi {LotName}. Vui lòng phản hồi trong 48 giờ.', 'InApp', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'COMPLAINT_CREATED', 'Có khiếu nại mới', NULL);
    INSERT INTO "NotificationTemplates" ("Id", "BodyTemplate", "Channel", "CreatedAtUtc", "IsActive", "Key", "TitleTemplate", "UpdatedAtUtc")
    VALUES (14, 'Bãi {LotName} tạm đóng. Booking {BookingCode} sẽ được hoàn tiền hoặc đổi bãi.', 'Sms', TIMESTAMPTZ '2026-10-01T00:00:00Z', TRUE, 'EMERGENCY_CLOSURE', 'Bãi đóng khẩn cấp', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_DeviceTokens_Token" ON "DeviceTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE INDEX "IX_DeviceTokens_UserId_IsRevoked" ON "DeviceTokens" ("UserId", "IsRevoked");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_NotificationPreferences_UserId_TemplateKey_Channel" ON "NotificationPreferences" ("UserId", "TemplateKey", "Channel");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_Status_RetryCount" ON "Notifications" ("Status", "RetryCount");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_TemplateId" ON "Notifications" ("TemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_UserId_IsRead_CreatedAtUtc" ON "Notifications" ("UserId", "IsRead", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_NotificationTemplates_Key_Channel" ON "NotificationTemplates" ("Key", "Channel");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"NotificationTemplates"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "NotificationTemplates") + 1,
            nextval(pg_get_serial_sequence('"NotificationTemplates"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092403_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003092403_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

