CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE TABLE "GateDevices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "Code" character varying(40) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "DeviceType" character varying(40) NOT NULL,
        "Position" character varying(40),
        "Status" character varying(40) NOT NULL,
        "LastSeenAtUtc" timestamp with time zone,
        "FirmwareVersion" character varying(40),
        "OfflinePublicKey" text,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_GateDevices" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE TABLE "ParkingSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "BookingId" integer,
        "BookingCode" character varying(30),
        "UserId" integer,
        "VehicleId" integer,
        "SlotId" integer,
        "SlotCode" character varying(20),
        "PlateNumber" character varying(15) NOT NULL,
        "VehicleType" character varying(40) NOT NULL,
        "IsWalkIn" boolean NOT NULL,
        "EntryAtUtc" timestamp with time zone NOT NULL,
        "CheckInMethod" character varying(40) NOT NULL,
        "EntryImagePath" character varying(512),
        "EntryOcrRaw" character varying(100),
        "EntryOcrConfidence" double precision,
        "CheckedInByStaffId" integer,
        "ExitAtUtc" timestamp with time zone,
        "CheckOutMethod" character varying(40),
        "ExitImagePath" character varying(512),
        "ExitOcrRaw" character varying(100),
        "ExitOcrConfidence" double precision,
        "CheckedOutByStaffId" integer,
        "Fee" numeric(18,2),
        "OverstayFee" numeric(18,2),
        "Status" character varying(40) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ParkingSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ParkingSessions_Exit" CHECK ("ExitAtUtc" IS NULL OR "ExitAtUtc" >= "EntryAtUtc")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE TABLE "Shifts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "StaffUserId" integer NOT NULL,
        "StartedAtUtc" timestamp with time zone NOT NULL,
        "EndedAtUtc" timestamp with time zone,
        "Status" character varying(40) NOT NULL,
        "CheckInCount" integer NOT NULL,
        "CheckOutCount" integer NOT NULL,
        "NoShowCancelCount" integer NOT NULL,
        "ManualExceptionCount" integer NOT NULL,
        "CashCollected" numeric(18,2) NOT NULL,
        "HandoverNote" character varying(1000),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE TABLE "GateEvents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ParkingLotId" integer NOT NULL,
        "ParkingSessionId" integer,
        "ShiftId" integer,
        "EventType" character varying(40) NOT NULL,
        "PlateNumber" character varying(15),
        "ImagePath" character varying(512),
        "OcrRaw" character varying(100),
        "OcrConfidence" double precision,
        "PerformedByUserId" integer,
        "Note" character varying(1000),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_GateEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GateEvents_ParkingSessions_ParkingSessionId" FOREIGN KEY ("ParkingSessionId") REFERENCES "ParkingSessions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_GateEvents_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_GateDevices_Code" ON "GateDevices" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_GateDevices_ParkingLotId_Status" ON "GateDevices" ("ParkingLotId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_GateEvents_EventType_CreatedAtUtc" ON "GateEvents" ("EventType", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_GateEvents_ParkingLotId_CreatedAtUtc" ON "GateEvents" ("ParkingLotId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_GateEvents_ParkingSessionId" ON "GateEvents" ("ParkingSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_GateEvents_ShiftId" ON "GateEvents" ("ShiftId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ParkingSessions_BookingId" ON "ParkingSessions" ("BookingId") WHERE "BookingId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ParkingSessions_Code" ON "ParkingSessions" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_ParkingSessions_OwnerProfileId_ParkingLotId_EntryAtUtc" ON "ParkingSessions" ("OwnerProfileId", "ParkingLotId", "EntryAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ParkingSessions_ParkingLotId_PlateNumber" ON "ParkingSessions" ("ParkingLotId", "PlateNumber") WHERE "Status" = 'Active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE INDEX "IX_Shifts_ParkingLotId_StartedAtUtc" ON "Shifts" ("ParkingLotId", "StartedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Shifts_StaffUserId" ON "Shifts" ("StaffUserId") WHERE "Status" = 'Open';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003102849_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003102849_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

