CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SourceService" character varying(50) NOT NULL,
        "UserId" integer,
        "OwnerProfileId" integer,
        "Action" character varying(100) NOT NULL,
        "EntityName" character varying(100) NOT NULL,
        "EntityId" character varying(50),
        "OldValuesJson" text,
        "NewValuesJson" text,
        "Reason" character varying(1000),
        "IpAddress" character varying(45),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE TABLE "FeatureFlags" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(100) NOT NULL,
        "IsEnabled" boolean NOT NULL,
        "Description" character varying(500),
        "UpdatedByUserId" integer,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_FeatureFlags" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE TABLE "Sanctions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerProfileId" integer NOT NULL,
        "ParkingLotId" integer,
        "Level" character varying(40) NOT NULL,
        "Reason" character varying(1000) NOT NULL,
        "EvidenceJson" text,
        "StartsAtUtc" timestamp with time zone NOT NULL,
        "EndsAtUtc" timestamp with time zone,
        "Status" character varying(40) NOT NULL,
        "PenaltyAmount" numeric(18,2),
        "IssuedByUserId" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Sanctions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE TABLE "SystemConfigs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(100) NOT NULL,
        "Value" character varying(1000) NOT NULL,
        "DataType" character varying(20) NOT NULL,
        "Description" character varying(500),
        "UpdatedByUserId" integer,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_SystemConfigs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE TABLE "RiskFlags" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SubjectType" character varying(40) NOT NULL,
        "SubjectId" integer NOT NULL,
        "RuleCode" character varying(60) NOT NULL,
        "Severity" character varying(40) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "EvidenceJson" text,
        "DueAtUtc" timestamp with time zone NOT NULL,
        "AssignedToUserId" integer,
        "ResolvedAtUtc" timestamp with time zone,
        "ResolutionNote" character varying(1000),
        "SanctionId" integer,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_RiskFlags" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RiskFlags_Sanctions_SanctionId" FOREIGN KEY ("SanctionId") REFERENCES "Sanctions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (1, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Nhận diện biển số OCR tại cổng (có trong demo MVP)', TRUE, 'FEATURE_AI_LPR', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (2, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Sơ đồ 2.5D/3D – stretch', FALSE, 'FEATURE_3D_MAP', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (3, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Tìm bãi bằng giọng nói – stretch', FALSE, 'FEATURE_AI_VOICE_SEARCH', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (4, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Chatbot FAQ – stretch', FALSE, 'FEATURE_AI_CHATBOT', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (5, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Bãi quảng cáo trên kết quả tìm kiếm – Phase 2', FALSE, 'FEATURE_SPONSORED_LISTING', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (6, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Vé tháng – Phase 2', FALSE, 'FEATURE_MONTHLY_PASS', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (7, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Thanh toán online qua VNPAY sandbox', TRUE, 'FEATURE_VNPAY', NULL, NULL);
    INSERT INTO "FeatureFlags" ("Id", "CreatedAtUtc", "Description", "IsEnabled", "Key", "UpdatedAtUtc", "UpdatedByUserId")
    VALUES (8, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'Thanh toán VietQR động tại cổng ra', TRUE, 'FEATURE_VIETQR_AT_GATE', NULL, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (1, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Thời gian giữ chỗ chờ thanh toán', 'BOOKING_HOLD_MINUTES', NULL, NULL, '15');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (2, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Ân hạn chờ tài xế đến trễ', 'CHECKIN_GRACE_PERIOD_MINUTES', NULL, NULL, '15');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (3, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Ân hạn miễn phí tính cước mỗi lượt', 'PARKING_BILLING_GRACE_PERIOD_MINUTES', NULL, NULL, '15');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (4, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hủy trước ≥ 60 phút hoàn 100%, sau đó hoàn 0%', 'CANCELLATION_WINDOW_MINUTES', NULL, NULL, '60');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (5, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Staff được hủy no-show sau mốc này', 'NO_SHOW_CANCEL_AFTER_MINUTES', NULL, NULL, '30');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (6, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Bãi Mức 0 phải duyệt booking trong thời gian này', 'MANUAL_LOT_APPROVAL_MINUTES', NULL, NULL, '10');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (7, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'decimal', 'Hoa hồng mặc định trên giao dịch hoàn tất', 'DEFAULT_COMMISSION_RATE', NULL, NULL, '0.10');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (8, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'string', 'Chu kỳ quyết toán cho chủ bãi', 'SETTLEMENT_CYCLE', NULL, NULL, 'WEEKLY');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (9, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hiệu lực mã OTP', 'OTP_EXPIRY_SECONDS', NULL, NULL, '300');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (10, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Số lần nhập sai OTP trước khi khóa', 'OTP_MAX_ATTEMPTS', NULL, NULL, '3');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (11, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Thời gian khóa sau khi sai OTP', 'OTP_LOCK_MINUTES', NULL, NULL, '15');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (12, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hiệu lực access token', 'JWT_ACCESS_TOKEN_HOURS', NULL, NULL, '24');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (13, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hiệu lực refresh token', 'JWT_REFRESH_TOKEN_DAYS', NULL, NULL, '7');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (14, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Số xe tối đa trong Garage cá nhân', 'MAX_VEHICLES_PER_USER', NULL, NULL, '10');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (15, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'decimal', 'Bán kính tìm bãi mặc định', 'SEARCH_RADIUS_KM', NULL, NULL, '5');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (16, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Biên an toàn chiều cao xe so với trần', 'HEIGHT_CLEARANCE_MARGIN_CM', NULL, NULL, '10');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (17, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Chu kỳ kiểm tra kết nối bãi', 'HEARTBEAT_INTERVAL_SECONDS', NULL, NULL, '60');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (18, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Số lần mất kết nối trước khi đánh dấu Stale', 'HEARTBEAT_MAX_FAILURES', NULL, NULL, '3');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (19, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'decimal', 'Ngưỡng tự mở barie theo kết quả OCR', 'OCR_AUTO_OPEN_MIN_CONFIDENCE', NULL, NULL, '0.90');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (20, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hạn chủ bãi phản hồi tranh chấp', 'OWNER_DISPUTE_RESPONSE_HOURS', NULL, NULL, '48');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (21, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hạn gửi khiếu nại sau sự việc', 'COMPLAINT_WINDOW_DAYS', NULL, NULL, '7');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (22, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Hạn cập nhật sơ đồ sau thay đổi thực tế', 'LAYOUT_UPDATE_DEADLINE_HOURS', NULL, NULL, '48');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (23, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'decimal', 'Phí chiếm dụng trụ sạc sau 30 phút sạc đầy', 'EV_IDLE_FEE_PER_15_MINUTES', NULL, NULL, '20000');
    INSERT INTO "SystemConfigs" ("Id", "CreatedAtUtc", "DataType", "Description", "Key", "UpdatedAtUtc", "UpdatedByUserId", "Value")
    VALUES (24, TIMESTAMPTZ '2026-10-01T00:00:00Z', 'int', 'Giới hạn request/phút cho mỗi client', 'API_RATE_LIMIT_PER_MINUTE', NULL, NULL, '100');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_EntityName_EntityId" ON "AuditLogs" ("EntityName", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_OwnerProfileId_CreatedAtUtc" ON "AuditLogs" ("OwnerProfileId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_UserId_CreatedAtUtc" ON "AuditLogs" ("UserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_FeatureFlags_Key" ON "FeatureFlags" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_RiskFlags_SanctionId" ON "RiskFlags" ("SanctionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_RiskFlags_Status_Severity_DueAtUtc" ON "RiskFlags" ("Status", "Severity", "DueAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_RiskFlags_SubjectType_SubjectId" ON "RiskFlags" ("SubjectType", "SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_Sanctions_OwnerProfileId_Status" ON "Sanctions" ("OwnerProfileId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE INDEX "IX_Sanctions_ParkingLotId" ON "Sanctions" ("ParkingLotId") WHERE [ParkingLotId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SystemConfigs_Key" ON "SystemConfigs" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"FeatureFlags"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "FeatureFlags") + 1,
            nextval(pg_get_serial_sequence('"FeatureFlags"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"SystemConfigs"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SystemConfigs") + 1,
            nextval(pg_get_serial_sequence('"SystemConfigs"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092506_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003092506_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

