CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE TABLE "Complaints" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(30) NOT NULL,
        "UserId" integer NOT NULL,
        "BookingId" integer,
        "BookingCode" character varying(30),
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "Category" character varying(40) NOT NULL,
        "Description" character varying(4000) NOT NULL,
        "EvidenceUrlsJson" text,
        "RequestedAmount" numeric(18,2),
        "Status" character varying(40) NOT NULL,
        "OwnerResponse" character varying(4000),
        "OwnerResponseDueAtUtc" timestamp with time zone,
        "OwnerRespondedAtUtc" timestamp with time zone,
        "EscalatedAtUtc" timestamp with time zone,
        "Resolution" character varying(4000),
        "ResolvedRefundAmount" numeric(18,2),
        "ResolvedByUserId" integer,
        "ResolvedAtUtc" timestamp with time zone,
        "PayoutHeld" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Complaints" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE TABLE "FaqArticles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Category" character varying(50) NOT NULL,
        "Question" character varying(500) NOT NULL,
        "Answer" character varying(4000) NOT NULL,
        "Audience" character varying(20) NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsPublished" boolean NOT NULL,
        "ViewCount" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_FaqArticles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE TABLE "OutboxMessages" (
        "Id" uuid NOT NULL,
        "EventType" character varying(200) NOT NULL,
        "PayloadJson" text NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "ProcessedAtUtc" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE TABLE "Reviews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "ReviewerName" character varying(150) NOT NULL,
        "ParkingLotId" integer NOT NULL,
        "OwnerProfileId" integer NOT NULL,
        "Rating" smallint NOT NULL,
        "Comment" character varying(2000),
        "OwnerReply" character varying(2000),
        "OwnerRepliedAtUtc" timestamp with time zone,
        "IsFlagged" boolean NOT NULL,
        "FlagReason" character varying(500),
        "IsHidden" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Reviews_Rating" CHECK ([Rating] BETWEEN 1 AND 5)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE TABLE "ComplaintMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ComplaintId" integer NOT NULL,
        "SenderParty" character varying(40) NOT NULL,
        "SenderUserId" integer,
        "Message" character varying(4000) NOT NULL,
        "AttachmentUrlsJson" text,
        "IsInternal" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ComplaintMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ComplaintMessages_Complaints_ComplaintId" FOREIGN KEY ("ComplaintId") REFERENCES "Complaints" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_ComplaintMessages_ComplaintId_CreatedAtUtc" ON "ComplaintMessages" ("ComplaintId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_Complaints_BookingId" ON "Complaints" ("BookingId") WHERE [BookingId] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Complaints_Code" ON "Complaints" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_Complaints_OwnerProfileId_Status" ON "Complaints" ("OwnerProfileId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_Complaints_Status_OwnerResponseDueAtUtc" ON "Complaints" ("Status", "OwnerResponseDueAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_Complaints_UserId" ON "Complaints" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_FaqArticles_IsPublished_Category_SortOrder" ON "FaqArticles" ("IsPublished", "Category", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_OutboxMessages_ProcessedAtUtc_OccurredAtUtc" ON "OutboxMessages" ("ProcessedAtUtc", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reviews_BookingId" ON "Reviews" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_ParkingLotId_IsHidden_CreatedAtUtc" ON "Reviews" ("ParkingLotId", "IsHidden", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261003092540_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261003092540_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

