// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;

#nullable disable

namespace NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20261002083857_AddDocumentCoverage")]
    partial class AddDocumentCoverage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("DeviceTokens", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Status", "RetryCount");

                    b.HasIndex("UserId", "IsRead", "CreatedAtUtc");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("QuietFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("QuietTo")
                        .HasColumnType("time");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TemplateKey", "Channel")
                        .IsUnique();

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Channel")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyTemplate = "Mã OTP Smart Parking của bạn là {Code}, hiệu lực 5 phút.",
                            Channel = "Sms",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "OTP_CODE",
                            TitleTemplate = "Mã xác thực"
                        },
                        new
                        {
                            Id = 2,
                            BodyTemplate = "Booking {BookingCode} tại {LotName} lúc {StartAt} đã được xác nhận.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "BOOKING_CONFIRMED",
                            TitleTemplate = "Đặt chỗ thành công"
                        },
                        new
                        {
                            Id = 3,
                            BodyTemplate = "Bạn đã đặt chỗ tại {LotName}, slot {SlotCode}, từ {StartAt} đến {EndAt}. Số tiền: {Amount}.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "BOOKING_CONFIRMED",
                            TitleTemplate = "Xác nhận đặt chỗ {BookingCode}"
                        },
                        new
                        {
                            Id = 4,
                            BodyTemplate = "Booking {BookingCode} đã hết 15 phút giữ chỗ do chưa thanh toán.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "BOOKING_HOLD_EXPIRED",
                            TitleTemplate = "Hết thời gian giữ chỗ"
                        },
                        new
                        {
                            Id = 5,
                            BodyTemplate = "Booking {BookingCode} bắt đầu lúc {StartAt}. Bạn có 15 phút ân hạn khi đến trễ.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "BOOKING_REMINDER",
                            TitleTemplate = "Sắp đến giờ đỗ xe"
                        },
                        new
                        {
                            Id = 6,
                            BodyTemplate = "Booking {BookingCode} đã hủy. Hoàn tiền: {RefundAmount}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "BOOKING_CANCELLED",
                            TitleTemplate = "Đã hủy booking"
                        },
                        new
                        {
                            Id = 7,
                            BodyTemplate = "Booking {BookingCode} đã bị hủy vì quá 30 phút chưa check-in.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "BOOKING_NO_SHOW",
                            TitleTemplate = "Booking bị hủy do không đến"
                        },
                        new
                        {
                            Id = 8,
                            BodyTemplate = "Xe {PlateNumber} đã vào {LotName} lúc {EntryAt}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "CHECKIN_SUCCESS",
                            TitleTemplate = "Xe đã vào bãi"
                        },
                        new
                        {
                            Id = 9,
                            BodyTemplate = "Xe {PlateNumber} ra lúc {ExitAt}. Tổng phí: {Amount}.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "CHECKOUT_RECEIPT",
                            TitleTemplate = "Xe đã ra bãi"
                        },
                        new
                        {
                            Id = 10,
                            BodyTemplate = "Thanh toán cho {BookingCode} không thành công. Vui lòng thử lại.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "PAYMENT_FAILED",
                            TitleTemplate = "Thanh toán thất bại"
                        },
                        new
                        {
                            Id = 11,
                            BodyTemplate = "Bãi {LotName} đã được duyệt và hiển thị trên Smart Parking.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "KYB_APPROVED",
                            TitleTemplate = "Bãi xe đã được duyệt"
                        },
                        new
                        {
                            Id = 12,
                            BodyTemplate = "Hồ sơ bãi {LotName} chưa được duyệt. Lý do: {Reason}.",
                            Channel = "Email",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "KYB_REJECTED",
                            TitleTemplate = "Hồ sơ bãi xe cần bổ sung"
                        },
                        new
                        {
                            Id = 13,
                            BodyTemplate = "Khiếu nại {ComplaintCode} cho bãi {LotName}. Vui lòng phản hồi trong 48 giờ.",
                            Channel = "InApp",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "COMPLAINT_CREATED",
                            TitleTemplate = "Có khiếu nại mới"
                        },
                        new
                        {
                            Id = 14,
                            BodyTemplate = "Bãi {LotName} tạm đóng. Booking {BookingCode} sẽ được hoàn tiền hoặc đổi bãi.",
                            Channel = "Sms",
                            CreatedAtUtc = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "EMERGENCY_CLOSURE",
                            TitleTemplate = "Bãi đóng khẩn cấp"
                        });
                });

            modelBuilder.Entity("ParkingManagement.SharedKernel.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.NotificationTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
