<Project Sdk="Microsoft.NET.Sdk">
  <!-- DOMAIN: Entity, quy táº¯c nghiá»‡p vá»¥ thuáº§n. Chá»‰ phá»¥ thuá»™c SharedKernel. -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\ParkingManagement.SharedKernel\ParkingManagement.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>
</Project>